### ISSUE TITLE
Things to fix before next language update

### ISSUE THREAD

**Issue by toyboot4e** [toyboot4e/ac-library-hs#4]
Requirements:
- [x] Implement the rest modules (#1)
- [x] Add documentations (#31)
- [x] Add `doctest` (#31)
- [x] LLVM should be optional
- [x] #46
- [x] #43
- [x] #41
- [x] Get access to Hackage (just ask for two people to endorse my account on Hackage)

Preferable:
- [x] Write benchmarks (#5) 
- [x] Optimize the library (#10)
- [x] Make the build faster (#51)

Optinonal:
- [x] Add sample `SegAct` instances: #40
- [ ] #32
- [ ] #22
- [x] Encirh `AtCoder.Extra` module (#42)
- [ ] Rename redundant qualified import names (`AC*`)
- [ ] Achieve 100% function test coverage

**Comment by toyboot4e** [comment]
All the modules other than `Extra` is ready. I'll first upload the package to Hackage and then tweak the `Extra` module.

**Comment by toyboot4e** [comment]
1.0.0.0 is published: https://hackage.haskell.org/package/ac-library-hs-1.0.0.0

Try it out after running `cabal update`.

**Comment by toyboot4e** [comment]
The extra module was enriched in 1.1.0.0. Almost done, closing.
